/**
 * Hub Autopilot — canonical agent registry (8 core agents).
 */

import type { AgentDefinition } from './types.js';

export const AGENT_REGISTRY: AgentDefinition[] = [
  {
    id: 'lead-concierge',
    name: 'Lead Concierge Agent',
    shortName: 'Lead Concierge',
    purpose: 'First-touch replies, intake routing, and hold language from web and portal inquiries.',
    capabilities: ['inbox_draft'],
    watchedSignals: ['new_inquiry', 'qualified_no_touch', 'lost_inquiry_followup'],
    proposedActions: ['draft_message', 'queue_approval'],
    runMode: 'queue_for_approval',
    priority: 7,
    approvalPolicy: {
      defaultRunMode: 'queue_for_approval',
      requiresApproval: true,
      approvalReason: 'Outbound client communication must be human-approved.',
    },
    safetyNotes: [
      'Never sends email automatically in current build.',
      'Sanitized drafts only — no PII echo in previews.',
    ],
  },
  {
    id: 'follow-up-hunter',
    name: 'Follow-Up Hunter Agent',
    shortName: 'Follow-Up Hunter',
    purpose: 'Detects stale proposals and nudges coordinators without duplicate spam.',
    capabilities: ['proposal_followup'],
    watchedSignals: ['proposal_sent_idle', 'proposal_viewed_no_deposit'],
    proposedActions: ['draft_message', 'schedule_task', 'queue_approval'],
    runMode: 'queue_for_approval',
    priority: 8,
    approvalPolicy: {
      defaultRunMode: 'queue_for_approval',
      requiresApproval: true,
      approvalReason: 'Proposal follow-ups change commercial terms perception.',
    },
    safetyNotes: ['Does not advance CRM stage automatically.', 'Respects cooldown between touches.'],
  },
  {
    id: 'booking-coordinator',
    name: 'Booking Coordinator Agent',
    shortName: 'Booking Coordinator',
    purpose: 'Prep packs, Kisi access, load-in windows, and BEO next-step hygiene.',
    capabilities: ['task_spawn', 'calendar_scan'],
    watchedSignals: ['automated_task_due', 'pre_event_window', 'unsigned_checklist'],
    proposedActions: ['schedule_task', 'draft_message', 'queue_approval'],
    runMode: 'queue_for_approval',
    priority: 9,
    approvalPolicy: {
      defaultRunMode: 'queue_for_approval',
      requiresApproval: true,
      approvalReason: 'Door codes and vendor timing affect on-site safety.',
    },
    safetyNotes: ['Kisi and access emails require explicit approval.', 'Internal tasks may auto-queue only.'],
  },
  {
    id: 'revenue-lift',
    name: 'Revenue Lift Agent',
    shortName: 'Revenue Lift',
    purpose: 'Surfaces small add-ons clients often accept (dessert station, extended hour, AV).',
    capabilities: ['upsell_surface'],
    watchedSignals: ['confirmed_partial_deposit', 'high_guest_count', 'recurring_series'],
    proposedActions: ['suggest_upsell', 'draft_message'],
    runMode: 'suggest',
    priority: 6,
    approvalPolicy: {
      defaultRunMode: 'suggest',
      requiresApproval: false,
      approvalReason: 'Upsell suggestions are advisory until coordinator promotes to proposal.',
      maxAutonomousAmount: 200,
    },
    safetyNotes: ['Never modifies signed contract totals.', 'Suggestions tied to event type patterns only.'],
  },
  {
    id: 'balance-guardian',
    name: 'Balance Guardian Agent',
    shortName: 'Balance Guardian',
    purpose: 'Deposit aging, balance due reminders, and AR-friendly payment paths.',
    capabilities: ['deposit_reminder'],
    watchedSignals: ['balance_due', 'deposit_received_partial', 'final_balance_window'],
    proposedActions: ['send_reminder', 'queue_approval'],
    runMode: 'queue_for_approval',
    priority: 10,
    approvalPolicy: {
      defaultRunMode: 'queue_for_approval',
      requiresApproval: true,
      approvalReason: 'Payment links and balance reminders are financial communications.',
    },
    safetyNotes: ['No charges or payment capture in demo engine.', 'Dual approval for nonprofit-facing mail.'],
  },
  {
    id: 'review-referral',
    name: 'Review & Referral Agent',
    shortName: 'Review & Referral',
    purpose: 'Post-event thank-you timing and review asks after closeout.',
    capabilities: ['post_event_review'],
    watchedSignals: ['event_completed', 'fundraiser_nonprofit'],
    proposedActions: ['draft_message'],
    runMode: 'autonomous_low_risk',
    priority: 4,
    approvalPolicy: {
      defaultRunMode: 'autonomous_low_risk',
      requiresApproval: false,
      approvalReason: 'Thank-you templates are low-risk when no payment language included.',
    },
    safetyNotes: ['Transactional preview only in demo.', 'Pauses if event disputed or lost.'],
  },
  {
    id: 'calendar-conflict',
    name: 'Calendar Conflict Agent',
    shortName: 'Calendar Conflict',
    purpose: 'Flags flip conflicts, same-day density, and late-night program risk on Event Space.',
    capabilities: ['calendar_scan'],
    watchedSignals: ['same_day_load', 'late_night_event', 'recurring_overlap'],
    proposedActions: ['flag_calendar', 'suppress_outbound'],
    runMode: 'observe_only',
    priority: 8,
    approvalPolicy: {
      defaultRunMode: 'observe_only',
      requiresApproval: true,
      approvalReason: 'Hold releases and calendar overrides need ops lead.',
    },
    safetyNotes: ['Can suppress other agents outbound when conflict detected.', 'Uses sanitized calendar seed only.'],
  },
  {
    id: 'owner-briefing',
    name: 'Owner Briefing Agent',
    shortName: 'Owner Briefing',
    purpose: 'Morning digest — priorities, balances, and agent queue for Jason Lavender.',
    capabilities: ['owner_digest'],
    watchedSignals: ['daily_priority_stack', 'agent_queue_depth', 'venue_kpi_delta'],
    proposedActions: ['owner_summary'],
    runMode: 'autonomous_low_risk',
    priority: 10,
    approvalPolicy: {
      defaultRunMode: 'autonomous_low_risk',
      requiresApproval: false,
      approvalReason: 'Internal owner digest — no client-facing send.',
    },
    safetyNotes: ['Never exposes raw inbox bodies.', 'Aggregates from structured seed + agent outputs.'],
  },
];

export const AGENT_BY_ID = Object.fromEntries(
  AGENT_REGISTRY.map(a => [a.id, a]),
) as Record<AgentDefinition['id'], AgentDefinition>;
