/** Auto-generated by scripts/import-hub-refresh.mjs — do not edit manually. */

export type HubRefreshManifest = {
  importBatchId: string;
  importedAt: string;
  sourceRoot: string;
  eventsParsed: number;
  uniquePvIds: number;
  contactsParsed: number;
  paymentsParsed: number;
  paymentsMatched: number;
  documentsMatched: number;
  invoicesMatched: number;
  beosMatched: number;
  agreementsMatched: number;
  menusMatched: number;
  eventSummariesMatched: number;
  staffBeosMatched: number;
  unmatchedCount: number;
  warningsCount: number;
  contaminationCount: number;
  contaminationAudit: string;
  duplicatePvIds: string[];
  financialTotals: { grandTotal: number; amountPaid: number; balanceDue: number };
  byStatus: Record<string, number>;
  folders: Record<string, { exists: boolean; fileCount: number }>;
  importCommands?: { audit: string; dryRun: string; apply: string };
};

export const HUB_REFRESH_AVAILABLE = true;

export const HUB_REFRESH_MANIFEST: HubRefreshManifest = {
  "importBatchId": "hub-refresh-2026-06-25T21-45-04",
  "importedAt": "2026-06-25T21:45:05.051Z",
  "sourceRoot": "C:\\Users\\Michaela\\Outside\\The Hub\\import",
  "eventsParsed": 317,
  "uniquePvIds": 317,
  "contactsParsed": 269,
  "paymentsParsed": 108,
  "paymentsMatched": 108,
  "documentsMatched": 0,
  "invoicesMatched": 0,
  "beosMatched": 0,
  "agreementsMatched": 0,
  "menusMatched": 0,
  "eventSummariesMatched": 0,
  "staffBeosMatched": 0,
  "unmatchedCount": 6,
  "warningsCount": 0,
  "contaminationCount": 0,
  "duplicatePvIds": [],
  "folders": {
    "01-events-master": {
      "exists": true,
      "fileCount": 1
    },
    "02-event-summaries": {
      "exists": true,
      "fileCount": 1
    },
    "03-beos": {
      "exists": true,
      "fileCount": 1
    },
    "04-staff-beos": {
      "exists": true,
      "fileCount": 1
    },
    "05-invoices": {
      "exists": true,
      "fileCount": 1
    },
    "06-agreements": {
      "exists": true,
      "fileCount": 1
    },
    "07-menus": {
      "exists": true,
      "fileCount": 1
    },
    "08-payments": {
      "exists": true,
      "fileCount": 1
    }
  },
  "financialTotals": {
    "grandTotal": 100434,
    "amountPaid": 28192.5,
    "balanceDue": 72641.5
  },
  "byStatus": {
    "completed": 67,
    "confirmed": 25,
    "lost": 152,
    "proposal_sent": 31,
    "balance_due": 15,
    "qualified": 16,
    "lead": 11
  },
  "contaminationAudit": "pass"
};
