/** Auto-generated by scripts/reset-hub-tenant-data.mjs — do not edit manually. */

export type HubResetManifest = {
  resetAt: string;
  tenantIds: string[];
  message: string;
  expectedFiles: string[];
  importCommands: string[];
};

export const HUB_RESET_MANIFEST: HubResetManifest | null = {
  "resetAt": "2026-06-25T17:28:50.490Z",
  "tenantIds": [
    "hub-wichita"
  ],
  "message": "HuB tenant data reset — ready for fresh Perfect Venue import",
  "expectedFiles": [
    "data/perfect-venue-import/Event Data *.xlsx",
    "data/perfect-venue-import/Proposal Data *.xlsx",
    "data/perfect-venue-import/Contact Data *.xlsx",
    "data/perfect-venue-import/Payment Data *.xlsx (optional)",
    "data/perfect-venue-import/PFevents.txt (optional text snapshot)"
  ],
  "importCommands": [
    "npm run import:perfect-venue",
    "npm run import:pfevents -- --apply"
  ]
};
